### PR TITLE
Initial implementation using objection instead of sequelize

### PR DESCRIPTION
**Pull request by dlom**
~~Not for merging yet!~~ Ready for merging now

### CODE REVIEW

**Comment by dlom** [comment]
@nvitha should be good to review/merge now, take a look

**Review by nvitha — APPROVED** [review]

**Comment by nvitha** [comment]
Gotta say fuck sequelize.

**Comment by dlom** [comment]
Closes #13

**Comment by nvitha** [comment]
You wanna close it or should I?

**Comment by dlom** [comment]
You should close the other PR

**Pull request merged**
