### PR TITLE
Added sequelize ORM and switch over login sytem to use it

### PR DESCRIPTION
**Pull request by nvitha**
You need to have a database with postgres installed to use this. Be sure when testing to run the install again after you have switched branches to this one in order to install the new packages this uses (pg, pg-hstore, sequelize, sequelize-cli).

The README shows the way to install this using `npm install`

### CODE REVIEW

**Comment by dlom** [comment]
What happened to `.env` by the way?

**Comment by nvitha** [comment]
It wasn't necessary anymore since sequelize uses their own config files.

**Comment by dlom** [comment]
You didn't commit any model code

**Comment by dlom** [comment]
Also the tests and codestyle checks are failing

**Pull request closed without merging**
